version: "3"
services:
  postgres-0:
    image: postgres:alpine
    container_name: postgres-0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urldb
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  urlshortener-service:
    image: bryannx/urlshortener
    command: bin/urlshortenerservice -Dplay.http.secret.key=6Z<_Xo^9QUAspP`rE6v@KF[KofLo`bLJs73c8`84SdYeLcMDCu_LdLoV;os@x;wj
    depends_on:
      - postgres-0
    ports:
      - 9000:9000
    volumes:
      - ./urlshortenerservice:/opt/urlshortenerservice
volumes:
  postgres-data:
    driver: local

